### ISSUE TITLE
Possibly Add More Tracking

### ISSUE THREAD

**Issue by mikebronner** [mikebronner/laravel-mixpanel#8]
Some articles to look through for smart tracking strategies:
- http://500.co/mixpanel-pitfalls-how-to-get-it-right/

### Acceptance Criteria

- [ ] Research referenced tracking strategy articles and identify ≥ 3 tracking improvements applicable to this package
- [ ] Each new tracking feature is configurable — opt-in or opt-out via config key
- [ ] Implemented tracking improvements include clear documentation in README
- [ ] Each new tracking feature has tests covering its behavior and config toggle
- [ ] No breaking changes to existing tracking behavior
- [ ] Implemented improvements are listed in CHANGELOG
